version: "3.9"
services:
  auth-service:
    env_file:
      - ./.env
    build:
      context: apps/be/auth-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      PREFIX: auth
      NODE_ENV: development
      NATS_CONNECTION_URL: nats://nats-dev:4222
      MONGO_CONNECTION_URI: "${MONGO_CONNECTION_URI}/auth"
      JWT_SECRET: secret
      SALT_TO_ROUNDS: ${SALT_TO_ROUNDS}
      GENERATE_PASSKEY_SECRET: ${GENERATE_PASSKEY_SECRET}
      REDIS_GRAPHQL_CONNECTION_URL: redis://redis-graphql:6379
      TWO_FA_TOKEN_EXIPRY: 7d
      INITIAL_TOKEN_EXPIRY: 1h
      EMAIL_VERIFICATION_LINK_EXPIRY: 1d
      EXPIRY_MINUTES: 5
      KAFKA_URI: kafka:9092
    depends_on:
      - zoo
      - kafka
      - mongo
      - redis-graphql
    networks:
      - app-network
  
  post-service:
    env_file:
      - ./.env
    build:
      context: apps/be/post-service
      dockerfile: Dockerfile
    ports:
      - "3009:3009"
    environment:
      PORT: 3009
      PREFIX: post
      NODE_ENV: development
      NATS_CONNECTION_URL: nats://nats-dev:4222
      MONGO_CONNECTION_URI: "${MONGO_CONNECTION_URI}/post"
      JWT_SECRET: secret
      SALT_TO_ROUNDS: ${SALT_TO_ROUNDS}
      GENERATE_PASSKEY_SECRET: ${GENERATE_PASSKEY_SECRET}
      REDIS_GRAPHQL_CONNECTION_URL: redis://redis-graphql:6379
      TWO_FA_TOKEN_EXIPRY: 7d
      INITIAL_TOKEN_EXPIRY: 1h
      EMAIL_VERIFICATION_LINK_EXPIRY: 1d
      EXPIRY_MINUTES: 5
    depends_on:
      - nats-dev
      - mongo
      - redis-graphql
    networks:
      - app-network

  front-web-service:
    env_file:
      - ./.env
    build:
      context: apps/be/front-web-service
      dockerfile: Dockerfile
    ports:
      - "3011:3011"
    environment:
      PORT: 3011
      PREFIX: front-web
      NODE_ENV: development
      NATS_CONNECTION_URL: nats://nats-dev:4222
      MONGO_CONNECTION_URI: "${MONGO_CONNECTION_URI}/front-web"
      JWT_SECRET: secret
      SALT_TO_ROUNDS: ${SALT_TO_ROUNDS}
      GENERATE_PASSKEY_SECRET: ${GENERATE_PASSKEY_SECRET}
      REDIS_GRAPHQL_CONNECTION_URL: redis://redis-graphql:6379
      TWO_FA_TOKEN_EXIPRY: 7d
      INITIAL_TOKEN_EXPIRY: 1h
      EMAIL_VERIFICATION_LINK_EXPIRY: 1d
      EXPIRY_MINUTES: 5
    depends_on:
      - nats-dev
      - mongo
      - redis-graphql
    networks:
      - app-network

  email-service:
    env_file:
      - ./.env
    build:
      context: apps/be/email-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
      PREFIX: email
      NODE_ENV: development
      NATS_CONNECTION_URL: nats://nats-dev:4222
      MONGO_CONNECTION_URI: "${MONGO_CONNECTION_URI}/email"
      JWT_SECRET: secret
      SALT_TO_ROUNDS: ${SALT_TO_ROUNDS}
      EMAIL: ${EMAIL}
      EMAIL_PASS: ${EMAIL_PASS}
      EMAIL_SERVICE: ${EMAIL_SERVICE}
      FE_APP_URL: ${FE_APP_URL}
      KAFKA_URI: kafka:9092
    depends_on:
      - zoo
      - kafka
      - mongo
    networks:
      - app-network

  file-service:
    env_file:
      - ./.env
    build:
      context: apps/be/file-service
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      PORT: 3003
      PREFIX: file
      NODE_ENV: development
      NATS_CONNECTION_URL: nats://nats-dev:4222
      MONGO_CONNECTION_URI: "${MONGO_CONNECTION_URI}/file"
      JWT_SECRET: secret
      SALT_TO_ROUNDS: ${SALT_TO_ROUNDS}
      FILE_URL: http://api.enochdev.com/file/images
      AWS_SECRET_ACCESS_KEY: HHeaB73J1sfsRduHmGN3JhQ8AQd5njUvReHY9WFGPp4
      AWS_ACCESS_KEY_ID: 452O44CXAKLTJN3BY4NH
      #AWS_DEFAULT_REGION :
      AWS_BUCKET: enochstaging
      DO_SPACES_ENDPOINT: ams3.digitaloceanspaces.com
      KAFKA_URI: kafka:9092
    volumes:
      - ./apps/be/file-service/src/:/app/src
      - /app/node_modules
      - ./apps/be/file-service/public:/app/public

    depends_on:
      - mongo
      - zoo
      - kafka
    networks:
      - app-network

  sms-service:
    env_file:
      - ./.env
    build:
      context: apps/be/sms-service
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    environment:
      PORT: 3004
      PREFIX: sms
      NODE_ENV: development
      NATS_CONNECTION_URL: nats://nats-dev:4222
      MONGO_CONNECTION_URI: "${MONGO_CONNECTION_URI}/sms"
      JWT_SECRET: secret
      SALT_TO_ROUNDS: ${SALT_TO_ROUNDS}
      VONAGE_API_SECRETE_KEY: ${VONAGE_API_SECRETE_KEY}
      VONAGE_API_KEY: ${VONAGE_API_KEY}
      EXPIRY_MINUTES: ${EXPIRY_MINUTES}
      YOUR_VIRTUAL_NUMBER: ${YOUR_VIRTUAL_NUMBER}
      KAFKA_URI: kafka:9092
    depends_on:
      - zoo
      - kafka
      - mongo
    networks:
      - app-network

  web3-service:
    env_file:
      - ./.env
    build:
      context: apps/be/web3-service
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    environment:
      PORT: 3005
      PREFIX: web3
      NODE_ENV: development
      MONGO_CONNECTION_URI: "${MONGO_CONNECTION_URI}/web3"
    depends_on:
      - mongo
    networks:
      - app-network    


  shop-service:
    env_file:
      - ./.env
    build:
      context: apps/be/shop-service
      dockerfile: Dockerfile
    ports:
      - "3006:3006"
    environment:
      PORT: 3006
      PREFIX: shop
      NODE_ENV: development
      MONGO_CONNECTION_URI: "${MONGO_CONNECTION_URI}/shop"
    depends_on:
      - mongo
    networks:
      - app-network

  zoo:
    image: confluentinc/cp-zookeeper:7.2.1
    hostname: zoo
    container_name: zoo
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo:2888:3888
    networks:
      - app-network  

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    hostname: kafka
    container_name: kafka
    ports:
      - "29092:29092" 
    environment:
      KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:29092,INTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1}
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
      KAFKAJS_NO_PARTITIONER_WARNING: 1 
    depends_on:
      - zoo
    networks:
      - app-network      

  enoch:
    env_file:
      - ./.env
    build:
      context: apps/fe/enoch
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - post-service

    environment:
      PORT: 3000
      NODE_ENV: development
      NATS_CONNECTION_URL: nats://nats-dev:4222
      JWT_SECRET: secret
    networks:
      - app-network

  # nats-dev:
  #   ports:
  #     - "4222:4222"
  #   image: nats-streaming:0.17.0
  #   networks:
  #     - app-network

  redis-graphql:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - ./data/redis:/data

  mongo:
    image: mongo
    #environment:
    #MONGO_INITDB_ROOT_USERNAME: root
    #MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - app-network
    volumes:
      - ./data/db:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017
    networks:
      - app-network

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/config/nginx-dev.conf:/etc/nginx/conf.d/node.template
      - ./nginx/html:/etc/nginx//html
      - ./nginx/ssl:/etc/nginx/certs
    command: 'bash -c "cat /etc/nginx/conf.d/node.template > /etc/nginx/conf.d/default.conf && nginx -g ''daemon off;''"'
    depends_on:
      - auth-service
      - post-service
      - email-service
      - file-service
      - enoch
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
