export const messages = {
  passwordRequired: "Please enter a password",
  passkeyRequired: "Please enter a passkey",
  emailRequired: "Please enter your mail id",
  emailStandard: {
    mailFormat: "Use the standard domain format, like example.com",
  },
  shortPassword: "Sorry that password is too short",
  longPassword: "Sorry that password is too long",
  passwordStandard: {
    uppercase: "Uppercase letter is missing",
    lowercase: "Lowercase letter is missing",
    number: "Number is missing",
    specialChar: "Special character is missing",
  },
  phoneNumberRequired: "Please enter a phone number",
  firstName: "Please enter your first name",
  lastName: "Please enter your last name",
  emailError: "The address doesn't seem right",
  confirmPassword: "Sorry, password doesn't match",
  requiredConfirmPassword: "Re-type your password",
  acceptTerms: "Please accept terms",
  authModeRequired: "Please select passkey",
  phoneRequired: "Please enter the phone number",
  phoneError: "Write the phone number in correct format",
  countryCode: "Please select the country code",
  otpRequired: "Please enter the OTP generated from the authenticator app",
  shortOTPError: "Please enter a six digit OTP",
  genderRequired: "Choose a valid gender",
  countryRequired: "Please select a country",
  hereForRequired: "Please select a purpose of using Enoch",
  relationshipStatusRequired: "Marital Status is Required",
  dateOfBirthRequired: "Please enter your Date of birth",
  fullName: "Full Name is required",
  bio: "Bio is required",
  website: "Website is required",
  loginSuccess: "Login Successfully",
  emailVerified: "Email verified successfully!",
  writePost: {
    video: {
      success: "Video has been uploaded",
    },
    photo: {
      success: "Photo has been uploaded",
    },
    document: {
      success: "Document has been uploaded",
    },
    poll: {
      success: "Poll posted",
    },
    text: {
      success: "Text posted",
    },
  },

  userExperience: {
    jobTitle: "Job Title is Required",
    employementType: "Please choose an employement type",
    company: "Company is required",
    location: "Location is required",
    startMonth: "Start month is required",
    startYear: "Start year is required",
    endMonth: "End month is required",
    endYear: "End year is required",
    industry: "Industry is required",
    description: "Description is required",
  },
};
