export const smartPhoneAuthSteps = {
  firstStep: {
    description: `Install Google authenticator on your smartphone (Andriod, iOS, 
        Windows)`,
    stepNumber: "1",
  },
  secondStep: {
    description: `To add /renew time based password, open the authenticator app 
      and scan the QR code below.`,
    stepNumber: "2",
  },
  thirdStep: {
    description: `Enter the time based password generated by the app below and click
      confirm to activate.`,
    stepNumber: "3",
  },
};
